### ISSUE TITLE
Jinja TemplateSyntaxError

### ISSUE THREAD

**Issue by DPicillo** [David-PIC/Linux-Grundlagen#2]
Ich habe aktuell ein Bug in der DEV Branch.
Ich versuche in der grundlegende-befehle.html den mit gegebenen JSON Strings in Aufgaben um zu wandeln.
Um nicht auf jeder Seite den gleichen Code zu verwenden, habe ich eine task.html angelegt.

Leider tritt folgender Fehler auf:

TemplateSyntaxError
jinja2.exceptions.TemplateSyntaxError: expected token 'end of statement block', got 'with'

**Comment by worldworm** [comment]
Ich glaube das hier ist keine Jinja2 Syntax, sondern stammt aus der [Django Syntax](https://docs.djangoproject.com/en/4.2/ref/templates/builtins/#include):
(Django und Jinja2 sind sehr ändlich, aber Django hat da einiges verändert soweit ich das verstehe)
```
{% include 'task.html' with task=task only %}
```

Versuche es mal so:
```
{% for task in tasks %}
  {% with task=task %}
    {% include "task.html" %}
  {% endwith %}
{% endfor %}
```

da die Variable gleich heißt, scheint aber auch folgendes zu klappen (ist ggf. etwas schöner):
```
{% for task in tasks %}
  {% include "task.html" %}
{% endfor %}
```
